#ifndef FREQBDCUGUI_GLOBAL_H
#define FREQBDCUGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FREQBDCUGUISHARED_LIBRARY)
#  define FREQBDCUGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define FREQBDCUGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FREQBDCUGUI_GLOBAL_H


