#ifndef SS1BBE_CJCSPARAMSETGUI_GLOBAL_H
#define SS1BBE_CJCSPARAMSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SS1BBE_CJCSPARAMSETGUI_LIBRARY)
#  define SS1BBE_CJCSPARAMSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SS1BBE_CJCSPARAMSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SS1BBE_CJCSPARAMSETGUI_GLOBAL_H


