#ifndef TESTNET_SWITCHGUI_GLOBAL_HU
#define TESTNET_SWITCHGUI_GLOBAL_HU

#include <QtCore/qglobal.h>

#if defined(TESTNET_SWITCHGUI_LIBRARY)
#  define TESTNET_SWITCHGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define TESTNET_SWITCHGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTNET_SWITCHGUI_GLOBAL_HU


