#ifndef DDTBBE_RECSETGUI_GLOBAL_H
#define DDTBBE_RECSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DDTBBE_RECSETGUI_LIBRARY)
#  define DDTBBE_RECSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define DDTBBE_RECSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DDTBBE_RECSETGUI_GLOBAL_H


