#ifndef USBBBE_ZKSETGUI_GLOBAL_H
#define USBBBE_ZKSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USBBBE_ZKSETGUI_LIBRARY)
#  define USBBBE_ZKSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define USBBBE_ZKSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USBBBE_ZKSETGUI_GLOBAL_H


