#ifndef SSBBE_OUTPUTSELSETGUI_GLOBAL_H
#define SSBBE_OUTPUTSELSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SSBBE_OUTPUTSELSETGUI_LIBRARY)
#  define SSBBE_OUTPUTSELSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SSBBE_OUTPUTSELSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SSBBE_OUTPUTSELSETGUI_GLOBAL_H


