#ifndef ZEROSTDDCUGUI_GLOBAL_H
#define ZEROSTDDCUGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZEROSTDDCUGUI_LIBRARY)
#  define ZEROSTDDCUGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZEROSTDDCUGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZEROSTDDCUGUI_GLOBAL_H


