#ifndef SS2BBE_MODUPARAMSETGUI_GLOBAL_H
#define SS2BBE_MODUPARAMSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SS2BBE_MODUPARAMSETGUI_LIBRARY)
#  define SS2BBE_MODUPARAMSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SS2BBE_MODUPARAMSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SS2BBE_MODUPARAMSETGUI_GLOBAL_H


