#ifndef SS2BBE_TCPARASETGUI_GLOBAL_H
#define SS2BBE_TCPARASETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SS2BBE_TCPARASETGUI_LIBRARY)
#  define SS2BBE_TCPARASETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SS2BBE_TCPARASETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SS2BBE_TCPARASETGUI_GLOBAL_H


