#ifndef SSWITCHDCUGUI_GLOBAL_HU
#define SSWITCHDCUGUI_GLOBAL_HU

#include <QtCore/qglobal.h>

#if defined(SSWITCHDCUGUI_LIBRARY)
#  define SSWITCHDCUGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SSWITCHDCUGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SSWITCHDCUGUI_GLOBAL_HU


