#ifndef DDTBBE_CODFRMSYNSETGUI_GLOBAL_H
#define DDTBBE_CODFRMSYNSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DDTBBE_CODFRMSYNSETGUI_LIBRARY)
#  define DDTBBE_CODFRMSYNSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define DDTBBE_CODFRMSYNSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DDTBBE_CODFRMSYNSETGUI_GLOBAL_H


