#ifndef SS2BBE_RCVPARAMSETGUI_GLOBAL_H
#define SS2BBE_RCVPARAMSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SS2BBE_RCVPARAMSETGUI_LIBRARY)
#  define SS2BBE_RCVPARAMSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SS2BBE_RCVPARAMSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SS2BBE_RCVPARAMSETGUI_GLOBAL_H


