#ifndef USBBBE_CODETMEMUSETGUI_GLOBAL_H
#define USBBBE_CODETMEMUSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USBBBE_CODETMEMUSETGUI_LIBRARY)
#  define USBBBE_CODETMEMUSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define USBBBE_CODETMEMUSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USBBBE_CODETMEMUSETGUI_GLOBAL_H


