#ifndef USBBBE_PMMODUSETGUI_GLOBAL_H
#define USBBBE_PMMODUSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USBBBE_PMMODUSETGUI_LIBRARY)
#  define USBBBE_PMMODUSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define USBBBE_PMMODUSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USBBBE_PMMODUSETGUI_GLOBAL_H


