#ifndef SSBBE_SYSPARAMSETGUI_GLOBAL_H
#define SSBBE_SYSPARAMSETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SSBBE_SYSPARAMSETGUI_LIBRARY)
#  define SSBBE_SYSPARAMSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SSBBE_SYSPARAMSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SSBBE_SYSPARAMSETGUI_GLOBAL_H


