#ifndef USBBBE_SYSPARASETGUI_GLOBAL_H
#define USBBBE_SYSPARASETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USBBBE_SYSPARASETGUI_LIBRARY)
#  define USBBBE_SYSPARASETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define USBBBE_SYSPARASETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USBBBE_SYSPARASETGUI_GLOBAL_H


