#ifndef SS2BBE_TMPARASETGUI_GLOBAL_H
#define SS2BBE_TMPARASETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SS2BBE_TMPARASETGUI_LIBRARY)
#  define SS2BBE_TMPARASETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SS2BBE_TMPARASETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SS2BBE_TMPARASETGUI_GLOBAL_H


