#ifndef TCPNCODESETGUI_GLOBAL_H
#define TCPNCODESETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TCPNCODESETGUI_LIBRARY)
#  define TCPNCODESETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define TCPNCODESETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TCPNCODESETGUI_GLOBAL_H


