#ifndef SS2PNCODESETGUI_GLOBAL_H
#define SS2PNCODESETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SS2PNCODESETGUI_LIBRARY)
#  define SS2PNCODESETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SS2PNCODESETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SS2PNCODESETGUI_GLOBAL_H


