#ifndef USBBBE_TMCJRECSETGUIGUI_GLOBAL_H
#define USBBBE_TMCJRECSETGUIGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USBBBE_TMCJRECSETGUISHARED_LIBRARY)
#  define USBBBE_TMCJRECSETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define USBBBE_TMCJRECSETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USBBBE_TMCJRECSETGUI_GLOBAL_H


