#ifndef DDTBBE_SYSPARASETGUI_GLOBAL_H
#define DDTBBE_SYSPARASETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DDTBBE_SYSPARASETGUI_LIBRARY)
#  define DDTBBE_SYSPARASETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define DDTBBE_SYSPARASETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DDTBBE_SYSPARASETGUI_GLOBAL_H


