#ifndef SSBBE_TMSIMU1PARASETGUI_GLOBAL_H
#define SSBBE_TMSIMU1PARASETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SSBBE_TMSIMU1PARASETGUI_LIBRARY)
#  define SSBBE_TMSIMU1PARASETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SSBBE_TMSIMU1PARASETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SSBBE_TMSIMU1PARASETGUI_GLOBAL_H


