#ifndef USBRSPDCUGUI_GLOBAL_H
#define USBRSPDCUGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USBRSPDCUGUI_LIBRARY)
#  define USBRSPDCUGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define USBRSPDCUGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USBRSPDCUGUI_GLOBAL_H


