#ifndef SSBBE_TMPARASETGUI_GLOBAL_H
#define SSBBE_TMPARASETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SSBBE_TMPARASETGUI_LIBRARY)
#  define SSBBE_TMPARASETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SSBBE_TMPARASETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SSBBE_TMPARASETGUI_GLOBAL_H


