#ifndef SS2RSPDCUGUI_GLOBAL_H
#define SS2RSPDCUGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SS2RSPDCUGUI_LIBRARY)
#  define SS2RSPDCUGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SS2RSPDCUGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SS2RSPDCUGUI_GLOBAL_H


