#ifndef USBBBE_CODETMPARASETGUI_GLOBAL_H
#define USBBBE_CODETMPARASETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(USBBBE_CODETMPARASETGUI_LIBRARY)
#  define USBBBE_CODETMPARASETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define USBBBE_CODETMPARASETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // USBBBE_CODETMPARASETGUI_GLOBAL_H


