#ifndef SS1PNCODESETGUI_GLOBAL_H
#define SS1PNCODESETGUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SS1PNCODESETGUI_LIBRARY)
#  define SS1PNCODESETGUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SS1PNCODESETGUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SS1PNCODESETGUI_GLOBAL_H


